-- Migration PostgreSQL para o Supabase.
-- Execute no SQL Editor do projeto Supabase.
-- Este arquivo cria somente as tabelas da aplicacao; nao use CREATE DATABASE/USE.

CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    celular VARCHAR(20),
    senha VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'usuario' CHECK (role IN ('admin', 'usuario')),
    ativo SMALLINT NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
    tentativas_login INTEGER NOT NULL DEFAULT 0,
    bloqueado_ate TIMESTAMP,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS membros_familia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    parentesco VARCHAR(50),
    usuario_id INTEGER REFERENCES usuarios(id) ON DELETE SET NULL,
    ativo SMALLINT NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categorias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('receita', 'despesa')),
    icone VARCHAR(50),
    ativo SMALLINT NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
    CONSTRAINT uq_categoria_tipo UNIQUE (nome, tipo)
);

CREATE TABLE IF NOT EXISTS cartoes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    banco VARCHAR(100),
    limite_total NUMERIC(10, 2) NOT NULL DEFAULT 0,
    dia_fechamento INTEGER,
    dia_vencimento INTEGER,
    membro_id INTEGER REFERENCES membros_familia(id) ON DELETE SET NULL,
    ativo SMALLINT NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS receitas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(150) NOT NULL,
    categoria_id INTEGER REFERENCES categorias(id) ON DELETE SET NULL,
    membro_id INTEGER REFERENCES membros_familia(id) ON DELETE SET NULL,
    valor NUMERIC(10, 2) NOT NULL,
    data_receita DATE NOT NULL,
    tipo VARCHAR(20) NOT NULL DEFAULT 'Variavel' CHECK (tipo IN ('Fixa', 'Variavel')),
    observacao TEXT,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS despesas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(150) NOT NULL,
    categoria_id INTEGER REFERENCES categorias(id) ON DELETE SET NULL,
    membro_id INTEGER REFERENCES membros_familia(id) ON DELETE SET NULL,
    cartao_id INTEGER REFERENCES cartoes(id) ON DELETE SET NULL,
    tipo VARCHAR(20) NOT NULL DEFAULT 'Variavel' CHECK (tipo IN ('Fixa', 'Variavel')),
    forma_pagamento VARCHAR(30) NOT NULL CHECK (forma_pagamento IN ('PIX', 'Dinheiro', 'Cartao de Credito', 'Cartao de Debito', 'Boleto')),
    valor_previsto NUMERIC(10, 2) NOT NULL DEFAULT 0,
    valor_real NUMERIC(10, 2) NOT NULL DEFAULT 0,
    data_prevista DATE,
    data_pagamento DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Previsto' CHECK (status IN ('Previsto', 'Pago', 'Atrasado')),
    observacao TEXT,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS parcelas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    despesa_id INTEGER NOT NULL REFERENCES despesas(id) ON DELETE CASCADE,
    numero_parcela INTEGER NOT NULL,
    total_parcelas INTEGER NOT NULL,
    valor_parcela NUMERIC(10, 2) NOT NULL,
    data_vencimento DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Pendente' CHECK (status IN ('Pendente', 'Pago'))
);

CREATE TABLE IF NOT EXISTS anotacoes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto VARCHAR(500) NOT NULL,
    data_agendamento DATE NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS metas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    descricao TEXT,
    valor_meta NUMERIC(10, 2) NOT NULL,
    valor_atual NUMERIC(10, 2) NOT NULL DEFAULT 0,
    data_inicio DATE,
    data_final DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Em andamento' CHECK (status IN ('Em andamento', 'Concluida', 'Cancelada')),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orcamentos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id INTEGER NOT NULL REFERENCES categorias(id) ON DELETE CASCADE,
    mes INTEGER NOT NULL,
    ano INTEGER NOT NULL,
    valor_limite NUMERIC(10, 2) NOT NULL
);

INSERT INTO usuarios (nome, email, senha, role, ativo)
VALUES ('Administrador', 'admin@casaorganizada.com',
        '$2y$10$TuPZmBiHeCdQa3Mvj0K7buMECyL91m1FTDeZyU2JUIjH7uV3AuJVK',
        'admin', 1)
ON CONFLICT (email) DO NOTHING;

INSERT INTO usuarios (nome, email, celular, senha, role, ativo)
VALUES ('Matheus', 'matheusviniciuscaieiras@gmail.com', '11942726317',
        '$2y$10$.Bt1YzAUAIpi87XlNhH0puZGAib256pZFNGP0fxRzFz2VE2CK/eB.',
        'usuario', 1)
ON CONFLICT (email) DO NOTHING;

INSERT INTO categorias (nome, tipo) VALUES
('Salario', 'receita'), ('Freelance', 'receita'), ('Outros', 'receita'),
('Alimentacao', 'despesa'), ('Moradia', 'despesa'), ('Transporte', 'despesa'),
('Saude', 'despesa'), ('Educacao', 'despesa'), ('Lazer', 'despesa'),
('Contas', 'despesa'), ('Compras', 'despesa'), ('Outros', 'despesa')
ON CONFLICT (nome, tipo) DO NOTHING;
