CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    celular VARCHAR(20),
    senha VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'usuario' CHECK (role IN ('admin', 'usuario')),
    ativo SMALLINT NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
    tentativas_login INTEGER NOT NULL DEFAULT 0,
    bloqueado_ate TIMESTAMP NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO usuarios (nome, email, senha, role, ativo)
SELECT 'Administrador', 'admin@casaorganizada.com',
       '$2y$10$TuPZmBiHeCdQa3Mvj0K7buMECyL91m1FTDeZyU2JUIjH7uV3AuJVK',
       'admin', 1
WHERE NOT EXISTS (
    SELECT 1 FROM usuarios WHERE email = 'admin@casaorganizada.com'
);

INSERT INTO usuarios (nome, email, celular, senha, role, ativo)
SELECT 'Matheus', 'matheusviniciuscaieiras@gmail.com', '11942726317',
       '$2y$10$.Bt1YzAUAIpi87XlNhH0puZGAib256pZFNGP0fxRzFz2VE2CK/eB.',
       'usuario', 1
WHERE NOT EXISTS (
    SELECT 1 FROM usuarios WHERE email = 'matheusviniciuscaieiras@gmail.com'
);

CREATE TABLE IF NOT EXISTS membros_familia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    parentesco VARCHAR(50),
    usuario_id INTEGER NULL,
    ativo SMALLINT NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_membro_usuario FOREIGN KEY (usuario_id)
      REFERENCES usuarios(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS categorias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('receita', 'despesa')),
    icone VARCHAR(50),
    ativo SMALLINT NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
    CONSTRAINT uq_categoria_tipo UNIQUE (nome, tipo)
);

CREATE TABLE IF NOT EXISTS cartoes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    banco VARCHAR(100),
    limite_total NUMERIC(10,2) NOT NULL DEFAULT 0,
    dia_fechamento INTEGER,
    dia_vencimento INTEGER,
    membro_id INTEGER NULL,
    ativo SMALLINT NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cartao_membro FOREIGN KEY (membro_id)
      REFERENCES membros_familia(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS receitas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(150) NOT NULL,
    categoria_id INTEGER NULL,
    membro_id INTEGER NULL,
    valor NUMERIC(10,2) NOT NULL,
    data_receita DATE NOT NULL,
    tipo VARCHAR(20) NOT NULL DEFAULT 'Variavel' CHECK (tipo IN ('Fixa', 'Variavel')),
    observacao TEXT,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_receita_categoria FOREIGN KEY (categoria_id)
      REFERENCES categorias(id) ON DELETE SET NULL,
    CONSTRAINT fk_receita_membro FOREIGN KEY (membro_id)
      REFERENCES membros_familia(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS despesas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(150) NOT NULL,
    categoria_id INTEGER NULL,
    membro_id INTEGER NULL,
    cartao_id INTEGER NULL,
    tipo VARCHAR(20) NOT NULL DEFAULT 'Variavel' CHECK (tipo IN ('Fixa', 'Variavel')),
    forma_pagamento VARCHAR(30) NOT NULL CHECK (forma_pagamento IN ('PIX', 'Dinheiro', 'Cartao de Credito', 'Cartao de Debito', 'Boleto')),
    valor_previsto NUMERIC(10,2) NOT NULL DEFAULT 0,
    valor_real NUMERIC(10,2) NOT NULL DEFAULT 0,
    data_prevista DATE NULL,
    data_pagamento DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Previsto' CHECK (status IN ('Previsto', 'Pago', 'Atrasado')),
    observacao TEXT,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_despesa_categoria FOREIGN KEY (categoria_id)
      REFERENCES categorias(id) ON DELETE SET NULL,
    CONSTRAINT fk_despesa_membro FOREIGN KEY (membro_id)
      REFERENCES membros_familia(id) ON DELETE SET NULL,
    CONSTRAINT fk_despesa_cartao FOREIGN KEY (cartao_id)
      REFERENCES cartoes(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS parcelas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    despesa_id INTEGER NOT NULL,
    numero_parcela INTEGER NOT NULL,
    total_parcelas INTEGER NOT NULL,
    valor_parcela NUMERIC(10,2) NOT NULL,
    data_vencimento DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Pendente' CHECK (status IN ('Pendente', 'Pago')),
    CONSTRAINT fk_parcela_despesa FOREIGN KEY (despesa_id)
      REFERENCES despesas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS anotacoes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto VARCHAR(500) NOT NULL,
    data_agendamento DATE NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS metas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    descricao TEXT,
    valor_meta NUMERIC(10,2) NOT NULL,
    valor_atual NUMERIC(10,2) NOT NULL DEFAULT 0,
    data_inicio DATE,
    data_final DATE,
    status VARCHAR(30) NOT NULL DEFAULT 'Em andamento' CHECK (status IN ('Em andamento', 'Concluida', 'Cancelada')),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orcamentos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id INTEGER NOT NULL,
    mes INTEGER NOT NULL,
    ano INTEGER NOT NULL,
    valor_limite NUMERIC(10,2) NOT NULL,
    CONSTRAINT fk_orcamento_categoria FOREIGN KEY (categoria_id)
      REFERENCES categorias(id) ON DELETE CASCADE
);

INSERT INTO categorias (nome, tipo) VALUES
('Salário', 'receita'),
('Freelance', 'receita'),
('Outros', 'receita'),
('Alimentação', 'despesa'),
('Moradia', 'despesa'),
('Transporte', 'despesa'),
('Saúde', 'despesa'),
('Educação', 'despesa'),
('Lazer', 'despesa'),
('Contas', 'despesa'),
('Compras', 'despesa'),
('Outros', 'despesa')
ON CONFLICT (nome, tipo) DO UPDATE
SET nome = EXCLUDED.nome;
